import * as fs from "node:fs";
import * as vscode from "vscode";

export function registerWasmDashboard(context: vscode.ExtensionContext) {
    console.log("📊 Registering WASM Dashboard webview...");

    // 1. Existing Webview Panel (Editor Tab)
    context.subscriptions.push(
        vscode.commands.registerCommand("exba.showDashboard", () => {
            console.log("📋 Opening Dashboard as Editor Panel...");
            WasmDashboardPanel.createOrShow(context.extensionUri);
        }),
    );

    // 2. New Webview View (Sidebar Sidepanel)
    const provider = new WasmDashboardViewProvider(context.extensionUri);
    context.subscriptions.push(
        vscode.window.registerWebviewViewProvider(WasmDashboardViewProvider.viewType, provider),
    );
    console.log("✅ Webview view provider registered for:", WasmDashboardViewProvider.viewType);

    // Command to focus the sidepanel dashboard
    context.subscriptions.push(
        vscode.commands.registerCommand("exba.focusDashboardView", () => {
            console.log("🎯 Executing focusDashboardView command...");
            vscode.commands
                .executeCommand("exba.dashboardView.focus")
                .then(() => console.log("✅ Dashboard view focused"))
                .catch((err) => console.error("❌ Failed to focus dashboard view:", err));
        }),
    );
}

export class WasmDashboardViewProvider implements vscode.WebviewViewProvider {
    public static readonly viewType = "exba.dashboardView";

    constructor(private readonly _extensionUri: vscode.Uri) {}

    public resolveWebviewView(
        webviewView: vscode.WebviewView,
        _context: vscode.WebviewViewResolveContext,
        _token: vscode.CancellationToken,
    ) {
        console.log("🔧 Resolving EXBA Dashboard webview...");

        try {
            webviewView.title = "";
            webviewView.description = "";
            webviewView.badge = { value: 0, tooltip: "" };
            webviewView.webview.options = {
                enableScripts: true,
                localResourceRoots: [vscode.Uri.joinPath(this._extensionUri, "dist")],
            };

            const webview = webviewView.webview;

            // Read the generated HTML to find hashed filenames
            const htmlPath = vscode.Uri.joinPath(
                this._extensionUri,
                "dist",
                "webview",
                "index.html",
            );
            let htmlContent = fs.readFileSync(htmlPath.fsPath, "utf8");

            // Replace hashed script/css references
            // The HTML generated by rsbuild has paths like "./bundle.xxx.js" and "./index.xxx.css"
            // We need to convert them to webview URIs
            htmlContent = htmlContent.replace(
                /src="\.\/(bundle\.[a-z0-9]+\.js)"/g,
                (_, filename) => {
                    const uri = webview.asWebviewUri(
                        vscode.Uri.joinPath(this._extensionUri, "dist", "webview", filename),
                    );
                    return `src="${uri.toString()}"`;
                },
            );
            htmlContent = htmlContent.replace(
                /href="\.\/(index\.[a-z0-9]+\.css)"/g,
                (_, filename) => {
                    const uri = webview.asWebviewUri(
                        vscode.Uri.joinPath(this._extensionUri, "dist", "webview", filename),
                    );
                    return `href="${uri.toString()}"`;
                },
            );

            const wasmUri = webview.asWebviewUri(
                vscode.Uri.joinPath(this._extensionUri, "dist", "wasm", "dashboard_engine.wasm"),
            );

            webview.html = htmlContent.replace(
                "<body>",
                `<body data-wasm-uri="${wasmUri.toString()}" data-mode="grid-menu">`,
            );

            console.log("✅ Dashboard webview HTML loaded successfully (grid-menu mode)");

            webview.onDidReceiveMessage((message) => {
                switch (message.command) {
                    case "showNotification":
                        vscode.window.showInformationMessage(message.payload.message);
                        return;
                    case "log":
                        console.log(`[Webview Log] ${message.payload.message}`);
                        return;
                    case "extensionAction":
                        vscode.window.showInformationMessage(
                            `Action triggered for extension: ${message.payload.name}`,
                        );
                        return;
                    case "openFullscreen":
                        vscode.commands.executeCommand("exba.showDashboard");
                        return;
                }
            });
        } catch (error) {
            console.error("❌ Failed to resolve dashboard webview:", error);
            webviewView.webview.html = `
                <html>
                    <body style="padding: 20px; font-family: system-ui;">
                        <h2 style="color: #f87171;">Failed to Load Dashboard</h2>
                        <p>${error}</p>
                    </body>
                </html>
            `;
        }
    }
}

class WasmDashboardPanel {
    public static currentPanel: WasmDashboardPanel | undefined;
    public static readonly viewType = "wasmDashboard";

    private readonly _panel: vscode.WebviewPanel;
    private readonly _extensionUri: vscode.Uri;
    private _disposables: vscode.Disposable[] = [];

    public static createOrShow(extensionUri: vscode.Uri) {
        const column = vscode.window.activeTextEditor
            ? vscode.window.activeTextEditor.viewColumn
            : undefined;

        if (WasmDashboardPanel.currentPanel) {
            WasmDashboardPanel.currentPanel.dispose();
            return;
        }

        const panel = vscode.window.createWebviewPanel(
            WasmDashboardPanel.viewType,
            "WASM Web Component Dashboard",
            column || vscode.ViewColumn.One,
            {
                enableScripts: true,
                localResourceRoots: [vscode.Uri.joinPath(extensionUri, "dist")],
            },
        );

        WasmDashboardPanel.currentPanel = new WasmDashboardPanel(panel, extensionUri);
    }

    private constructor(panel: vscode.WebviewPanel, extensionUri: vscode.Uri) {
        this._panel = panel;
        this._extensionUri = extensionUri;
        this._update();
        this._panel.onDidDispose(() => this.dispose(), null, this._disposables);

        // Handle messages from the webview
        this._panel.webview.onDidReceiveMessage(
            (message) => {
                switch (message.command) {
                    case "showNotification":
                        vscode.window.showInformationMessage(message.payload.message);
                        return;
                    case "log":
                        console.log(`[Webview Log] ${message.payload.message}`);
                        return;
                    case "extensionAction":
                        vscode.window.showInformationMessage(
                            `Action triggered for extension: ${message.payload.name}`,
                        );
                        return;
                }
            },
            null,
            this._disposables,
        );
    }

    public dispose() {
        WasmDashboardPanel.currentPanel = undefined;
        this._panel.dispose();

        while (this._disposables.length) {
            const x = this._disposables.pop();
            if (x) {
                x.dispose();
            }
        }
    }

    private _update() {
        const webview = this._panel.webview;

        const htmlPath = vscode.Uri.joinPath(this._extensionUri, "dist", "webview", "index.html");
        let htmlContent = fs.readFileSync(htmlPath.fsPath, "utf8");

        // Replace hashed script/css references
        htmlContent = htmlContent.replace(/src="\.\/(bundle\.[a-z0-9]+\.js)"/g, (_, filename) => {
            const uri = webview.asWebviewUri(
                vscode.Uri.joinPath(this._extensionUri, "dist", "webview", filename),
            );
            return `src="${uri.toString()}"`;
        });
        htmlContent = htmlContent.replace(/href="\.\/(index\.[a-z0-9]+\.css)"/g, (_, filename) => {
            const uri = webview.asWebviewUri(
                vscode.Uri.joinPath(this._extensionUri, "dist", "webview", filename),
            );
            return `href="${uri.toString()}"`;
        });

        const wasmUri = webview.asWebviewUri(
            vscode.Uri.joinPath(this._extensionUri, "dist", "wasm", "dashboard_engine.wasm"),
        );

        this._panel.webview.html = htmlContent.replace(
            "<body>",
            `<body data-wasm-uri="${wasmUri.toString()}">`,
        );
    }
}
